#!/usr/bin/env -S nix shell nixpkgs#gdb nixpkgs#lldb -c sh

set -e

for bin in result*/bin/*; do
    echo "$bin"
    case "$(basename "$(basename "$bin")")" in
        cargo-miri)
            "$bin" miri -h > /dev/null;;
        rust-demangler)
            ;;
        *)
            "$bin" --help > /dev/null
    esac
done
